export const SET_CITY = 'SET_CITY';
export const SET_DETAILS = 'SET_DETAILS';
export const RECENT_CITY = 'RECENT_CITY';
export const IS_OPEN = 'IS_OPEN';
export const VISIBLE = 'VISIBLE';
export const SET_VIDEO = 'SET_VIDEO';

export const FETCH_WEATHER_START = 'FETCH_WEATHER_START';
export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';

export const FETCH_DAYS_START = 'FETCH_DAYS_START';
export const FETCH_DAYS_SUCCESS = 'FETCH_DAYS_SUCCESS';